apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
  labels:
    app: school-internal
  name: school-internal-headless
  namespace: rongke-dev-s
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: school-internal
  sessionAffinity: None
  type: ClusterIP
