// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.2
// source: api/org/orgInfo.proto

package org

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParentOrgInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShortName string `protobuf:"bytes,3,opt,name=shortName,proto3" json:"shortName,omitempty"`
}

func (x *ParentOrgInfo) Reset() {
	*x = ParentOrgInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_org_orgInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParentOrgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentOrgInfo) ProtoMessage() {}

func (x *ParentOrgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_org_orgInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentOrgInfo.ProtoReflect.Descriptor instead.
func (*ParentOrgInfo) Descriptor() ([]byte, []int) {
	return file_api_org_orgInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ParentOrgInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParentOrgInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParentOrgInfo) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

type OrgInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentOrg   *ParentOrgInfo `protobuf:"bytes,3,opt,name=parentOrg,proto3" json:"parentOrg,omitempty"`
	LevelTypeId int64          `protobuf:"varint,4,opt,name=levelTypeId,proto3" json:"levelTypeId,omitempty"`
}

func (x *OrgInfo) Reset() {
	*x = OrgInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_org_orgInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgInfo) ProtoMessage() {}

func (x *OrgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_org_orgInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgInfo.ProtoReflect.Descriptor instead.
func (*OrgInfo) Descriptor() ([]byte, []int) {
	return file_api_org_orgInfo_proto_rawDescGZIP(), []int{1}
}

func (x *OrgInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrgInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrgInfo) GetParentOrg() *ParentOrgInfo {
	if x != nil {
		return x.ParentOrg
	}
	return nil
}

func (x *OrgInfo) GetLevelTypeId() int64 {
	if x != nil {
		return x.LevelTypeId
	}
	return 0
}

var File_api_org_orgInfo_proto protoreflect.FileDescriptor

var file_api_org_orgInfo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x72, 0x67, 0x2f, 0x6f, 0x72, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x70, 0x69, 0x2e, 0x6f, 0x72, 0x67,
	0x22, 0x51, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x07, 0x4f, 0x72, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x42, 0x18, 0x0a, 0x07, 0x61,
	0x70, 0x69, 0x2e, 0x6f, 0x72, 0x67, 0x50, 0x01, 0x5a, 0x0b, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x72,
	0x67, 0x3b, 0x6f, 0x72, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_org_orgInfo_proto_rawDescOnce sync.Once
	file_api_org_orgInfo_proto_rawDescData = file_api_org_orgInfo_proto_rawDesc
)

func file_api_org_orgInfo_proto_rawDescGZIP() []byte {
	file_api_org_orgInfo_proto_rawDescOnce.Do(func() {
		file_api_org_orgInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_org_orgInfo_proto_rawDescData)
	})
	return file_api_org_orgInfo_proto_rawDescData
}

var file_api_org_orgInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_org_orgInfo_proto_goTypes = []interface{}{
	(*ParentOrgInfo)(nil), // 0: api.org.ParentOrgInfo
	(*OrgInfo)(nil),       // 1: api.org.OrgInfo
}
var file_api_org_orgInfo_proto_depIdxs = []int32{
	0, // 0: api.org.OrgInfo.parentOrg:type_name -> api.org.ParentOrgInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_org_orgInfo_proto_init() }
func file_api_org_orgInfo_proto_init() {
	if File_api_org_orgInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_org_orgInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParentOrgInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_org_orgInfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_org_orgInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_org_orgInfo_proto_goTypes,
		DependencyIndexes: file_api_org_orgInfo_proto_depIdxs,
		MessageInfos:      file_api_org_orgInfo_proto_msgTypes,
	}.Build()
	File_api_org_orgInfo_proto = out.File
	file_api_org_orgInfo_proto_rawDesc = nil
	file_api_org_orgInfo_proto_goTypes = nil
	file_api_org_orgInfo_proto_depIdxs = nil
}
